#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
   Copyright (C) 2014 David Colmenero - D_Skywalk
    http://david.dantoine.org

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   higher any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software Foundation,
   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
"""

# Example for Zelda aLttP :D

# safe value (not in table used in replaces)
SAFE = "@"

# end value for an end repeating value
ENDVAL = "FF"

# replace this table with your values
# TODO: made a generator :P
TABLE = {
        "00":"A",
        "01":"B",
        "02":"C",
        "03":"D",
        "04":"E",
        "05":"F",
        "06":"G",
        "07":"H",
        "08":"I",
        "09":"J",
        "0A":"K",
        "0B":"L",
        "0C":"M",
        "0D":"N",
        "0E":"O",
        "0F":"P",
        "10":"Q",
        "11":"R",
        "12":"S",
        "13":"T",
        "14":"U",
        "15":"V",
        # "16":"W", # simbolo
        "17":"é",
        "18":"Y",
        "19":"Z",
        "1A":"a",
        "1B":"b",
        "1C":"c",
        "1D":"d",
        "1E":"e",
        "1F":"f",
        "20":"g",
        "21":"h",
        "22":"i",
        "23":"j",
        "24":"k",
        "25":"l",
        "26":"m",
        "27":"n",
        "28":"o",
        "29":"p",
        "2A":"q",
        "2B":"r",
        "2C":"s",
        "2D":"t",
        "2E":"u",
        "2F":"v",
        "30":"ó",
        "31":"x",
        "32":"y",
        "33":"z",
        "34":"0",
        "35":"1",
        "36":"2",
        "37":"3",
        "38":"4",
        "39":"5",
        "3A":"6",
        "3B":"7",
        "3C":"8",
        "3D":"9",
        "3E":"!",
        "3F":"?",
        # "4C":"-", no usado... mirar comillas
        "41":".",
        "42":",",
        "43":"[43]",
        "44":"|>",
        "45":"(",
        "46":")",
        "47":"ñ",
        "48":"ú",
        "49":"á",
        "4C":"\"",
        "51":"í",
        "5B":"[A]",
        "5C":"[B]",
        "5D":"[X]",
        "5E":"[Y]",
        "59":" ",
        "60":"[60]",
        "61":"[61]",
        "16":"[S1]", # hylian symbols
        "40":"[S2]",
        "5A":"[S3]",
        "68":"[Choose]",
        "71":"[Choose2]",
        "6A":"[Name]",
        "73":"[Scroll]",
        "7E":"[Waitkey]",
        "74":"[1]",
        "75":"[2]",
        "76":"[3]",
        "7F":"[END]\n\n\n", # using linux endline (\r\n for win32... i think)
        "8A":"[Espacio 2]",

        "8B":" en",
        "8C":" la ",
        "8D":" el ",
        "8E":" de ",
        "8F":"ien",
        "90":"tra",
        "91":" de",
        "92":"te ",
        "93":"ar",
        "94":"a ",
        "95":"ada",
        "96":"es",
        "97":"as",
        "98":"o ",
        "99":" con",
        "9A":"ero",
        "9B":"ado",
        "9C":"e ",
        "9D":"que",
        "9E":"en",
        "9F":"al",
        "A0":"os ",
        "A1":"ora",
        "A2":"nte",
        "A3":" al",
        "A4":"lo ",
        "A5":"or",
        "A6":"os",
        "A7":"er",
        "A8":"aci",
        "A9":"res",
        "AA":" que ",
        "AB":" es",
        "AC":"el",
        "AD":"los ",
        "AE":"tar",
        "AF":" se",
        "B0":", ",
        "B1":"ro",
        "B2":" de l",
        "B3":" est",
        "B4":"re",
        "B5":"on",
        "B6":"an",
        "B7":"pued",
        "B8":" del",
        "B9":"ás ",
        "BA":"la",
        "BB":"ti",
        "BC":"la ",
        "BD":"Es",
        "BE":"to",
        "BF":"ta",
        "C0":"para",
        "C1":"uer",
        "C2":"ier",
        "C3":" un ",
        "C4":" por",
        "C5":"oder",
        "C6":"da",
        "C7":"in",
        "C8":"cu",
        "C9":" ha",
        "CA":"per",
        "CB":"ano",
        "CC":" ve",
        "CD":"cer",
        "CE":"lo",
        "CF":" no ",
        "D0":"ic",
        "D1":"ra",
        "D2":"ab",
        "D3":"ir",
        "D4":" una",
        "D5":"undo",
        "D6":"es ",
        "D7":"as ",
        "D8":"con",
        "D9":"a, ",
        "DA":"te",
        "DB":" m",
        "DC":"gu",
        "DD":" tu",
        "DE":"ando",
        "DF":" p",
        "E0":"de",
        "E1":"le",
        "E2":"ol",
        "E3":"o, ",
        "E4":"ten",
        "E5":"lle",
        "E6":" a ",
        "E7":"aba",
        "E8":"com",

}

"""
' en la  el  de ientra dete ara adaesaso  coneroadoe queenalos orante allo oroseracires que  esellos tar se, ro de l estreonanpued delás latila Estotaparauerier un  poroderdaincu haperano vecerlo no icraabir unaundoes as cona, te mgu tuando pdeleolo, tenlle a abacom'
"""
